branch-defaults:
  default:
    environment: builderbook-9-end-env
environment-defaults:
  builderbook-9-end-env:
    branch: null
    repository: null
global:
  application_name: builderbook-9-end-app
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
